// 插件说明：PuertsMixin 插件在蓝图编辑器工具栏添加 “Mixin” 按钮
// 功能：从当前正在编辑的蓝图获取资产路径，将 /Game 映射到项目目录下 TypeScript/Blueprints，
//      生成/打开对应的 TypeScript 混入文件，并尝试使用 VSCode 或 Trae 打开该文件
// 作者：AutoGenerated by Trae AI Assistant
// 注意：遵循项目中文注释规范（.cpp 文件头部注释、详细中文说明）
// Copyright Epic Games, Inc. All Rights Reserved.

#include "PuertsMixin.h"
#include "PuertsMixinStyle.h"
#include "PuertsMixinCommands.h"
#include "Toolbars/BlueprintToolbar.h"
#include "Toolbars/PuertsMixinEditorToolbar.h"
#include "Misc/CoreDelegates.h"
#include "Editor.h"
#include "ISettingsModule.h"
#include "ISettingsSection.h"
#include "PuertsMixinSettings.h"
#include "ContentBrowserModule.h"
#include "Framework/MultiBox/MultiBoxBuilder.h"
#include "Engine/Blueprint.h"
#include "Widgets/SMixinPathDialog.h"

#define LOCTEXT_NAMESPACE "FPuertsMixinModule"

void FPuertsMixinModule::StartupModule()
{
	// 模块启动：初始化样式与命令

	FPuertsMixinStyle::Initialize();
	FPuertsMixinStyle::ReloadTextures();

	FPuertsMixinCommands::Register();

	// 注册设置面板
	RegisterSettings();

	// 注册引擎初始化完成回调，避免过早加载 Kismet 模块导致 Crash
	FCoreDelegates::OnPostEngineInit.AddRaw(this, &FPuertsMixinModule::OnPostEngineInit);

	// 创建工具栏实例，但暂不初始化
	BlueprintToolbar = MakeShareable(new FBlueprintToolbar);

	// 注册 ContentBrowser 右键菜单扩展
	FContentBrowserModule& ContentBrowserModule =
		FModuleManager::LoadModuleChecked<FContentBrowserModule>(TEXT("ContentBrowser"));
	TArray<FContentBrowserMenuExtender_SelectedAssets>& ExtenderDelegates =
		ContentBrowserModule.GetAllAssetViewContextMenuExtenders();
	ExtenderDelegates.Add(
		FContentBrowserMenuExtender_SelectedAssets::CreateRaw(
			this, &FPuertsMixinModule::OnExtendContentBrowserAssetMenu
		)
	);
	ContentBrowserExtenderHandle = ExtenderDelegates.Last().GetHandle();
}

void FPuertsMixinModule::ShutdownModule()
{
	// 模块关闭：反注册菜单与样式、释放资源

	// 取消注册 ContentBrowser 扩展
	if (FContentBrowserModule* ContentBrowserModule =
		FModuleManager::GetModulePtr<FContentBrowserModule>(TEXT("ContentBrowser")))
	{
		TArray<FContentBrowserMenuExtender_SelectedAssets>& ExtenderDelegates =
			ContentBrowserModule->GetAllAssetViewContextMenuExtenders();
		ExtenderDelegates.RemoveAll([this](const FContentBrowserMenuExtender_SelectedAssets& Delegate) {
			return Delegate.GetHandle() == ContentBrowserExtenderHandle;
		});
	}

	UnregisterSettings();

	FCoreDelegates::OnPostEngineInit.RemoveAll(this);

	FPuertsMixinStyle::Shutdown();

	FPuertsMixinCommands::Unregister();
}

void FPuertsMixinModule::RegisterSettings()
{
	if (ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings"))
	{
		SettingsModule->RegisterSettings(
			"Project", "Plugins", "PuertsMixin",
			LOCTEXT("PuertsMixinSettingsName", "PuertsMixin"),
			LOCTEXT("PuertsMixinSettingsDescription", "Configure Puerts Mixin Plugin Settings"),
			GetMutableDefault<UPuertsMixinSettings>()
		);
	}
}

void FPuertsMixinModule::UnregisterSettings()
{
	if (ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings"))
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "PuertsMixin");
	}
}

void FPuertsMixinModule::OnPostEngineInit()
{
	if (!GEditor)
	{
		return;
	}

	// 引擎初始化完成后再初始化工具栏，此时可以安全加载 Kismet 模块
	if (BlueprintToolbar.IsValid())
	{
		BlueprintToolbar->Initialize();
	}
}

TSharedRef<FExtender> FPuertsMixinModule::OnExtendContentBrowserAssetMenu(const TArray<FAssetData>& SelectedAssets)
{
	TSharedRef<FExtender> MenuExtender = MakeShareable(new FExtender());

	// 检查选中的资产中是否有蓝图
	bool bHasBlueprints = false;
	for (const FAssetData& Asset : SelectedAssets)
	{
		if (Asset.AssetClassPath == UBlueprint::StaticClass()->GetClassPathName())
		{
			bHasBlueprints = true;
			break;
		}
	}

	if (bHasBlueprints)
	{
		MenuExtender->AddMenuExtension(
			"CommonAssetActions",
			EExtensionHook::After,
			nullptr,
			FMenuExtensionDelegate::CreateRaw(
				this,
				&FPuertsMixinModule::AddMixinMenuEntry,
				SelectedAssets
			)
		);
	}

	return MenuExtender;
}

void FPuertsMixinModule::AddMixinMenuEntry(FMenuBuilder& MenuBuilder, TArray<FAssetData> SelectedAssets)
{
	// 过滤出蓝图资产
	TArray<FAssetData> BlueprintAssets;
	for (const FAssetData& Asset : SelectedAssets)
	{
		if (Asset.AssetClassPath == UBlueprint::StaticClass()->GetClassPathName())
		{
			BlueprintAssets.Add(Asset);
		}
	}

	if (BlueprintAssets.Num() == 0)
	{
		return;
	}

	// 根据选中数量显示不同的菜单文本
	FText MenuLabel = BlueprintAssets.Num() == 1
		? LOCTEXT("CreateMixin", "Create Mixin")
		: FText::Format(LOCTEXT("CreateMixinMultiple", "Create Mixin ({0} Blueprints)"), FText::AsNumber(BlueprintAssets.Num()));

	FText MenuTooltip = BlueprintAssets.Num() == 1
		? LOCTEXT("CreateMixin_Tooltip", "Generate TypeScript Mixin file for this Blueprint")
		: LOCTEXT("CreateMixinMultiple_Tooltip", "Generate TypeScript Mixin files for selected Blueprints");

	MenuBuilder.AddMenuEntry(
		MenuLabel,
		MenuTooltip,
		FSlateIcon(FPuertsMixinStyle::GetStyleSetName(), "PuertsMixin.PluginAction"),
		FUIAction(FExecuteAction::CreateRaw(this, &FPuertsMixinModule::OnCreateMixinFromAssets, BlueprintAssets))
	);
}

void FPuertsMixinModule::OnCreateMixinFromAsset(FAssetData AssetData)
{
	// 加载蓝图资产
	UBlueprint* Blueprint = Cast<UBlueprint>(AssetData.GetAsset());
	if (!Blueprint)
	{
		return;
	}

	// 调用核心 Mixin 创建逻辑
	FPuertsMixinEditorToolbar::CreateMixinForBlueprint(Blueprint);
}

void FPuertsMixinModule::OnCreateMixinFromAssets(TArray<FAssetData> SelectedAssets)
{
	if (SelectedAssets.Num() == 0)
	{
		return;
	}

	// 单选时使用原有逻辑（显示完整路径对话框）
	if (SelectedAssets.Num() == 1)
	{
		OnCreateMixinFromAsset(SelectedAssets[0]);
		return;
	}

	// 多选时：先选择目录，再批量创建
	FString TargetDirectory;
	if (!SMixinPathDialog::ShowDirectoryDialog(TargetDirectory))
	{
		// 用户取消或选择了无效目录
		return;
	}

	// 加载所有蓝图
	TArray<UBlueprint*> Blueprints;
	for (const FAssetData& AssetData : SelectedAssets)
	{
		UBlueprint* Blueprint = Cast<UBlueprint>(AssetData.GetAsset());
		if (Blueprint)
		{
			Blueprints.Add(Blueprint);
		}
	}

	if (Blueprints.Num() > 0)
	{
		FPuertsMixinEditorToolbar::CreateMixinsForBlueprints(Blueprints, TargetDirectory);
	}
}

#undef LOCTEXT_NAMESPACE

IMPLEMENT_MODULE(FPuertsMixinModule, PuertsMixin)
