// 插件说明：PuertsMixin 插件在蓝图编辑器工具栏添加 “Mixin” 按钮
// 功能：从当前正在编辑的蓝图获取资产路径，将 /Game 映射到项目目录下 TypeScript/Blueprints，
//      生成/打开对应的 TypeScript 混入文件，并尝试使用 VSCode 或 Trae 打开该文件
// 作者：AutoGenerated by Trae AI Assistant
// 注意：遵循项目中文注释规范（.cpp 文件头部注释、详细中文说明）
// Copyright Epic Games, Inc. All Rights Reserved.

#include "PuertsMixin.h"
#include "PuertsMixinStyle.h"
#include "PuertsMixinCommands.h"
#include "Toolbars/BlueprintToolbar.h"
#include "Misc/CoreDelegates.h"
#include "Editor.h"
#include "ISettingsModule.h"
#include "ISettingsSection.h"
#include "PuertsMixinSettings.h"

#define LOCTEXT_NAMESPACE "FPuertsMixinModule"

void FPuertsMixinModule::StartupModule()
{
	// 模块启动：初始化样式与命令

	FPuertsMixinStyle::Initialize();
	FPuertsMixinStyle::ReloadTextures();

	FPuertsMixinCommands::Register();

	// 注册设置面板
	RegisterSettings();

	// 注册引擎初始化完成回调，避免过早加载 Kismet 模块导致 Crash
	FCoreDelegates::OnPostEngineInit.AddRaw(this, &FPuertsMixinModule::OnPostEngineInit);

	// 创建工具栏实例，但暂不初始化
	BlueprintToolbar = MakeShareable(new FBlueprintToolbar);
}

void FPuertsMixinModule::ShutdownModule()
{
	// 模块关闭：反注册菜单与样式、释放资源

	UnregisterSettings();

	FCoreDelegates::OnPostEngineInit.RemoveAll(this);

	FPuertsMixinStyle::Shutdown();

	FPuertsMixinCommands::Unregister();
}

void FPuertsMixinModule::RegisterSettings()
{
	if (ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings"))
	{
		SettingsModule->RegisterSettings(
			"Project", "Plugins", "PuertsMixin",
			LOCTEXT("PuertsMixinSettingsName", "PuertsMixin"),
			LOCTEXT("PuertsMixinSettingsDescription", "Configure Puerts Mixin Plugin Settings"),
			GetMutableDefault<UPuertsMixinSettings>()
		);
	}
}

void FPuertsMixinModule::UnregisterSettings()
{
	if (ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings"))
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "PuertsMixin");
	}
}

void FPuertsMixinModule::OnPostEngineInit()
{
	if (!GEditor)
	{
		return;
	}

	// 引擎初始化完成后再初始化工具栏，此时可以安全加载 Kismet 模块
	if (BlueprintToolbar.IsValid())
	{
		BlueprintToolbar->Initialize();
	}
}

#undef LOCTEXT_NAMESPACE

IMPLEMENT_MODULE(FPuertsMixinModule, PuertsMixin)
